// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Activities struct {
	ID          int    `json:"id"`
	Type        string `json:"type"`
	Description string `json:"description"`
	FromUserID  int    `json:"fromUserId"`
	ToUserID    int    `json:"toUserId"`
	UserID      int    `json:"userId"`
	Amount      string `json:"amount"`
	Date        string `json:"date"`
	IsConfirmed bool   `json:"isConfirmed"`
}

type CurrentMealsResponse struct {
	ID              int    `json:"id"`
	Name            string `json:"name"`
	TotalAmount     string `json:"totalAmount"`
	TotalMealsCount int    `json:"totalMealsCount"`
}

type Dashboard struct {
	TotalUsers          int                    `json:"totalUsers"`
	TotalMeals          int                    `json:"totalMeals"`
	TotalDebts          string                 `json:"totalDebts"`
	TotalCredits        string                 `json:"totalCredits"`
	TobDebtsPerUser     []*TobDebtsPerUser     `json:"tobDebtsPerUser"`
	TotalCreditsPerUser []*TotalCreditsPerUser `json:"totalCreditsPerUser"`
}

type Debt struct {
	ID          int    `json:"id"`
	FromUserID  int    `json:"fromUserId"`
	ToUserID    int    `json:"toUserId"`
	Amount      string `json:"amount"`
	MealsCount  int    `json:"mealsCount"`
	CreateDate  string `json:"createDate"`
	UpdatedDate string `json:"updatedDate"`
	IsConfirmed bool   `json:"isConfirmed"`
	MealID      int    `json:"mealId"`
}

type DebtDetail struct {
	ID           int          `json:"id"`
	FromUserID   int          `json:"from_user_id"`
	ToUserID     int          `json:"to_user_id"`
	FromUserName string       `json:"from_user_name"`
	ToUserName   string       `json:"to_user_name"`
	Amount       string       `json:"amount"`
	MealsCount   int          `json:"meals_count"`
	CreateDate   string       `json:"create_date"`
	IsConfirmed  bool         `json:"is_confirmed"`
	Type         string       `json:"type"`
	MealID       *int         `json:"meal_id,omitempty"`
	PaymentID    *int         `json:"payment_id,omitempty"`
	MealInfo     *MealInfo    `json:"meal_info,omitempty"`
	PaymentInfo  *PaymentInfo `json:"payment_info,omitempty"`
}

type Meal struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Date        string `json:"date"`
	TotalAmount string `json:"totalAmount"`
	UserID      int    `json:"userId"`
	Description string `json:"description"`
	CreateDate  string `json:"createDate"`
	UpdatedDate string `json:"updatedDate"`
	UserIds     string `json:"userIds"`
	Products    string `json:"products"`
}

type MealInfo struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Date        string  `json:"date"`
	TotalAmount string  `json:"total_amount"`
}

type MealInput struct {
	Name        string `json:"name"`
	Date        string `json:"date"`
	UserID      int    `json:"userId"`
	TotalAmount string `json:"totalAmount"`
	UserIds     string `json:"userIds"`
	Description string `json:"description"`
	Produkts    string `json:"produkts"`
}

type Mutation struct {
}

type Payment struct {
	ID          int    `json:"id"`
	FromUserID  int    `json:"fromUserId"`
	ToUserID    int    `json:"toUserId"`
	Amount      string `json:"amount"`
	Description string `json:"description"`
	Date        string `json:"date"`
	IsConfirmed bool   `json:"isConfirmed"`
}

type PaymentInfo struct {
	ID          int     `json:"id"`
	Description *string `json:"description,omitempty"`
	Date        string  `json:"date"`
	Amount      string  `json:"amount"`
}

type PaymentInput struct {
	FromUserID  int    `json:"fromUserId"`
	ToUserID    int    `json:"toUserId"`
	Amount      string `json:"amount"`
	Description string `json:"description"`
}

type Query struct {
}

type TobDebtsPerUser struct {
	UserID int    `json:"userId"`
	Amount string `json:"amount"`
}

type TotalCreditsPerUser struct {
	UserID int    `json:"userId"`
	Amount string `json:"amount"`
}

type UpdateUserInput struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
}

type User struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Debts       string `json:"debts"`
	Credits     string `json:"credits"`
	CreateDate  string `json:"createDate"`
	UpdatedDate string `json:"updatedDate"`
	PhoneNumber string `json:"phoneNumber"`
	Admin       bool   `json:"admin"`
}

type UserInput struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Admin bool   `json:"admin"`
}

type Response struct {
	Status  string `json:"status"`
	Message string `json:"message"`
	Success bool   `json:"success"`
}
