// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Activities struct {
	ID          int    `json:"id"`
	Type        string `json:"type"`
	Description string `json:"description"`
	FromUserID  int    `json:"fromUserId"`
	ToUserID    int    `json:"toUserId"`
	UserID      int    `json:"userId"`
	Amount      string `json:"amount"`
	Date        string `json:"date"`
}

type Dashboard struct {
	TotalUsers          int                    `json:"totalUsers"`
	TotalMeals          int                    `json:"totalMeals"`
	TotalDebts          string                 `json:"totalDebts"`
	TotalCredits        string                 `json:"totalCredits"`
	TobDebtsPerUser     []*TobDebtsPerUser     `json:"tobDebtsPerUser"`
	TotalCreditsPerUser []*TotalCreditsPerUser `json:"totalCreditsPerUser"`
}

type Debt struct {
	ID          int    `json:"id"`
	FromUserID  int    `json:"fromUserId"`
	ToUserID    int    `json:"toUserId"`
	Amount      string `json:"amount"`
	MealsCount  int    `json:"mealsCount"`
	CreateDate  string `json:"createDate"`
	UpdatedDate string `json:"updatedDate"`
}

type Meal struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Date        string `json:"date"`
	TotalAmount string `json:"totalAmount"`
	UserID      int    `json:"userId"`
	Description string `json:"description"`
	CreateDate  string `json:"createDate"`
	UpdatedDate string `json:"updatedDate"`
	UserIds     string `json:"userIds"`
}

type MealInput struct {
	Name        string `json:"name"`
	Date        string `json:"date"`
	UserID      int    `json:"userId"`
	TotalAmount string `json:"totalAmount"`
	UserIds     string `json:"userIds"`
	Description string `json:"description"`
}

type Mutation struct {
}

type Payment struct {
	ID          int    `json:"id"`
	FromUserID  int    `json:"fromUserId"`
	ToUserID    int    `json:"toUserId"`
	Amount      string `json:"amount"`
	Description string `json:"description"`
	Date        string `json:"date"`
}

type PaymentInput struct {
	FromUserID  int    `json:"fromUserId"`
	ToUserID    int    `json:"toUserId"`
	Amount      string `json:"amount"`
	Description string `json:"description"`
}

type Query struct {
}

type TobDebtsPerUser struct {
	UserID int    `json:"userId"`
	Amount string `json:"amount"`
}

type TotalCreditsPerUser struct {
	UserID int    `json:"userId"`
	Amount string `json:"amount"`
}

type User struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Debts       string `json:"debts"`
	Credits     string `json:"credits"`
	CreateDate  string `json:"createDate"`
	UpdatedDate string `json:"updatedDate"`
	PhoneNumber string `json:"phoneNumber"`
}

type Response struct {
	Status  string `json:"status"`
	Message string `json:"message"`
	Success bool   `json:"success"`
}
