package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"my-backend/graph/model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, content string) (*model.Response, error) {
	return GetControllerService(ctx).CreatePost(content)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string) (*model.Response, error) {
	return GetControllerService(ctx).CreateUser(name, email)
}

// CreateMeal is the resolver for the createMeal field.
func (r *mutationResolver) CreateMeal(ctx context.Context, meal model.MealInput) (*model.Response, error) {
	return GetControllerService(ctx).CreateMeal(meal)
}

// CreatePayment is the resolver for the createPayment field.
func (r *mutationResolver) CreatePayment(ctx context.Context, payment model.PaymentInput) (*model.Response, error) {
	return GetControllerService(ctx).CreatePayment(payment)
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context) ([]*model.User, error) {
	return GetControllerService(ctx).GetUsers()
}

// GetMeals is the resolver for the getMeals field.
func (r *queryResolver) GetMeals(ctx context.Context) ([]*model.Meal, error) {
	return GetControllerService(ctx).GetMeals()
}

// GetPayments is the resolver for the getPayments field.
func (r *queryResolver) GetPayments(ctx context.Context) ([]*model.Payment, error) {
	return GetControllerService(ctx).GetPayment()
}

// GetDebts is the resolver for the getDebts field.
func (r *queryResolver) GetDebts(ctx context.Context) ([]*model.Debt, error) {
	return GetControllerService(ctx).GetDebts()
}

// GetActivities is the resolver for the getActivities field.
func (r *queryResolver) GetActivities(ctx context.Context) ([]*model.Activities, error) {
	return GetControllerService(ctx).GetActivities()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
